# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Pipfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install --dev
            pwd
            ls

      - save_cache:
          paths:
            - $HOME/.local/share/virtualenvs
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}

      - store_artifacts:
          path: htmlcov/
          destination: htmlcov/

  deploy-develop:
    docker:
      - image: circleci/python:3.6.1
    working_directory: /tmp/my-project
    steps:
      - run:
          name: This is develop
          command: |
            echo "This is develop"
            ls /home/circleci/repo
            pwd

  deploy-master:
    docker:
      - image: ubuntu:14.04
    working_directory: /tmp/my-project
    steps:
      - run:
          name: This is master
          command: |
            echo "This is master"
            ls /home/circleci/repo
            pwd



workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-develop:
          requires:
            - build
          filters:
            branches:
              only: develop
      - deploy-master:
          requires:
            - build
          filters:
            branches:
              only: master
